# Generated by Django 5.2.1 on 2025-05-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='full_name',
            field=models.CharField(blank=True, help_text='Используется только в админке и при импорте', max_length=255, verbose_name='Полное наименование подразделения'),
        ),
        migrations.AddField(
            model_name='position',
            name='full_name',
            field=models.CharField(blank=True, help_text='Используется только в админке и при импорте', max_length=255, verbose_name='Полное наименование должности'),
        ),
    ]
