# Generated by Django 5.2.1 on 2025-05-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_full_name_position_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pass_svg',
            field=models.FileField(blank=True, null=True, upload_to='pass_result/', verbose_name='Пропуск'),
        ),
    ]
