# Generated by Django 5.2.1 on 2025-06-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_pass_svg'),
        ('employees', '0003_migrate_pass_status'),
    ]

    operations = [
    ]
